# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import bbpy.pbuf.app_pb2 as app__pb2


class BiobtreeServiceStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
            '/pbuf.BiobtreeService/Search',
            request_serializer=app__pb2.SearchRequest.SerializeToString,
            response_deserializer=app__pb2.SearchResponse.FromString,
        )
        self.Mapping = channel.unary_unary(
            '/pbuf.BiobtreeService/Mapping',
            request_serializer=app__pb2.MappingRequest.SerializeToString,
            response_deserializer=app__pb2.MappingResponse.FromString,
        )
        self.Entry = channel.unary_unary(
            '/pbuf.BiobtreeService/Entry',
            request_serializer=app__pb2.EntryRequest.SerializeToString,
            response_deserializer=app__pb2.EntryResponse.FromString,
        )
        self.Page = channel.unary_unary(
            '/pbuf.BiobtreeService/Page',
            request_serializer=app__pb2.PageRequest.SerializeToString,
            response_deserializer=app__pb2.PageResponse.FromString,
        )
        self.Filter = channel.unary_unary(
            '/pbuf.BiobtreeService/Filter',
            request_serializer=app__pb2.FilterRequest.SerializeToString,
            response_deserializer=app__pb2.FilterResponse.FromString,
        )
        self.Meta = channel.unary_unary(
            '/pbuf.BiobtreeService/Meta',
            request_serializer=app__pb2.MetaRequest.SerializeToString,
            response_deserializer=app__pb2.MetaResponse.FromString,
        )
        self.ListGenomes = channel.unary_unary(
            '/pbuf.BiobtreeService/ListGenomes',
            request_serializer=app__pb2.ListGenomesRequest.SerializeToString,
            response_deserializer=app__pb2.ListGenomesResponse.FromString,
        )


class BiobtreeServiceServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def Search(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Mapping(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Entry(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Page(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Filter(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Meta(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListGenomes(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BiobtreeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Search': grpc.unary_unary_rpc_method_handler(
            servicer.Search,
            request_deserializer=app__pb2.SearchRequest.FromString,
            response_serializer=app__pb2.SearchResponse.SerializeToString,
        ),
        'Mapping': grpc.unary_unary_rpc_method_handler(
            servicer.Mapping,
            request_deserializer=app__pb2.MappingRequest.FromString,
            response_serializer=app__pb2.MappingResponse.SerializeToString,
        ),
        'Entry': grpc.unary_unary_rpc_method_handler(
            servicer.Entry,
            request_deserializer=app__pb2.EntryRequest.FromString,
            response_serializer=app__pb2.EntryResponse.SerializeToString,
        ),
        'Page': grpc.unary_unary_rpc_method_handler(
            servicer.Page,
            request_deserializer=app__pb2.PageRequest.FromString,
            response_serializer=app__pb2.PageResponse.SerializeToString,
        ),
        'Filter': grpc.unary_unary_rpc_method_handler(
            servicer.Filter,
            request_deserializer=app__pb2.FilterRequest.FromString,
            response_serializer=app__pb2.FilterResponse.SerializeToString,
        ),
        'Meta': grpc.unary_unary_rpc_method_handler(
            servicer.Meta,
            request_deserializer=app__pb2.MetaRequest.FromString,
            response_serializer=app__pb2.MetaResponse.SerializeToString,
        ),
        'ListGenomes': grpc.unary_unary_rpc_method_handler(
            servicer.ListGenomes,
            request_deserializer=app__pb2.ListGenomesRequest.FromString,
            response_serializer=app__pb2.ListGenomesResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'pbuf.BiobtreeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
